"""empty message

Revision ID: 20187deb9dcd
Revises: 
Create Date: 2018-04-25 11:29:54.863594

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '20187deb9dcd'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cms_user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('_password', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=50), nullable=False),
    sa.Column('join_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.drop_table('spider_manage')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('spider_manage',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('host_name', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('ip_address', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('port_num', mysql.VARCHAR(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.drop_table('cms_user')
    # ### end Alembic commands ###
