"""empty message

Revision ID: 1306eb0a6c32
Revises: 56904b093758
Create Date: 2018-06-24 10:25:44.401146

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1306eb0a6c32'
down_revision = '56904b093758'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('host_list',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('host_name', sa.String(length=50), nullable=False),
    sa.Column('ip_address', sa.String(length=50), nullable=False),
    sa.Column('port_num', sa.String(length=50), nullable=False),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('host_list')
    # ### end Alembic commands ###
