"""empty message

Revision ID: 1d72de779ca4
Revises: 1306eb0a6c32
Create Date: 2018-07-25 11:27:13.404850

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1d72de779ca4'
down_revision = '1306eb0a6c32'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('host_list', sa.Column('pwd', sa.VARCHAR(length=50), nullable=True))
    op.add_column('host_list', sa.Column('user', sa.VARCHAR(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('host_list', 'user')
    op.drop_column('host_list', 'pwd')
    op.add_column('clients', sa.Column('host_name', sa.VARCHAR(length=50), nullable=True))
    # ### end Alembic commands ###
