"""empty message

Revision ID: 4bbc17675d03
Revises: 5b6577474659
Create Date: 2018-08-21 17:47:40.919032

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4bbc17675d03'
down_revision = '5b6577474659'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project_list',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_name', sa.VARCHAR(length=50), nullable=False),
    sa.Column('join_time', sa.VARCHAR(length=50), nullable=False),
    sa.Column('status', sa.VARCHAR(length=50), nullable=False),
    sa.Column('version', sa.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('project_list')
    # ### end Alembic commands ###
