"""empty message

Revision ID: d583ea6dff05
Revises: ac6cee1c6149
Create Date: 2018-08-21 17:46:21.442486

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd583ea6dff05'
down_revision = 'ac6cee1c6149'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('host_list')
    op.drop_table('users')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('username', sa.VARCHAR(length=50), nullable=False),
    sa.Column('_password', sa.VARCHAR(length=320), nullable=False),
    sa.Column('join_time', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('host_list',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('host_name', sa.VARCHAR(length=50), nullable=False),
    sa.Column('ip_address', sa.VARCHAR(length=50), nullable=False),
    sa.Column('port_num', sa.VARCHAR(length=50), nullable=False),
    sa.Column('create_time', sa.DATETIME(), nullable=True),
    sa.Column('user', sa.VARCHAR(length=50), nullable=True),
    sa.Column('pwd', sa.VARCHAR(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
