"""empty message

Revision ID: e5dd93c817a1
Revises: 1d72de779ca4
Create Date: 2018-07-25 12:54:37.916819

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e5dd93c817a1'
down_revision = '1d72de779ca4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('clients')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clients',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=50), nullable=False),
    sa.Column('ip', sa.VARCHAR(length=50), nullable=False),
    sa.Column('port', sa.INTEGER(), nullable=False),
    sa.Column('user', sa.VARCHAR(length=50), nullable=True),
    sa.Column('pwd', sa.VARCHAR(length=50), nullable=True),
    sa.Column('create_time', sa.DATETIME(), nullable=True),
    sa.Column('host_name', sa.VARCHAR(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
